# Generated by Django 4.1.7 on 2023-03-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badminton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('Pharmacy', 'Pharmacy'), ('BBA', 'BBA'), ('Law', 'Law'), ('Fashion Design', 'Fashion Design'), ('English', 'English')], max_length=20)),
                ('captainname', models.CharField(max_length=20)),
                ('cid', models.IntegerField()),
                ('name1', models.CharField(max_length=20)),
                ('id1', models.IntegerField()),
                ('name2', models.CharField(max_length=20)),
                ('id2', models.IntegerField()),
                ('name3', models.CharField(max_length=20)),
                ('id3', models.IntegerField()),
            ],
        ),
    ]
