# Generated by Django 4.1.7 on 2023-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_badminton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('Pharmacy', 'Pharmacy'), ('BBA', 'BBA'), ('Law', 'Law'), ('Fashion Design', 'Fashion Design'), ('English', 'English')], max_length=20)),
                ('captainname', models.CharField(max_length=20)),
                ('coachname', models.CharField(max_length=20)),
                ('cid', models.IntegerField()),
                ('name1', models.CharField(max_length=20)),
                ('id1', models.IntegerField()),
                ('name2', models.CharField(max_length=20)),
                ('id2', models.IntegerField()),
                ('name3', models.CharField(max_length=20)),
                ('id3', models.IntegerField()),
                ('name4', models.CharField(max_length=20)),
                ('id4', models.IntegerField()),
                ('name5', models.CharField(max_length=20)),
                ('id5', models.IntegerField()),
                ('name6', models.CharField(max_length=20)),
                ('id6', models.IntegerField()),
                ('name7', models.CharField(max_length=20)),
                ('id7', models.IntegerField()),
                ('name8', models.CharField(max_length=20)),
                ('id8', models.IntegerField()),
                ('name9', models.CharField(max_length=20)),
                ('id9', models.IntegerField()),
                ('name10', models.CharField(max_length=20)),
                ('id10', models.IntegerField()),
                ('name11', models.CharField(max_length=20)),
                ('id11', models.IntegerField()),
                ('name12', models.CharField(max_length=20)),
                ('id12', models.IntegerField()),
                ('name13', models.CharField(max_length=20)),
                ('id13', models.IntegerField()),
            ],
        ),
    ]
