# Generated by Django 4.1.7 on 2023-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_catalogue_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='catalogue',
            field=models.CharField(choices=[('P', 'Present'), ('E', 'Ex'), ('O', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
    ]
