# Generated by Django 4.1.7 on 2023-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_time', models.CharField(blank=True, max_length=200)),
                ('football_time', models.CharField(blank=True, max_length=200)),
                ('volleyball_time', models.CharField(blank=True, max_length=200)),
                ('kabaddi_time', models.CharField(blank=True, max_length=200)),
                ('chess_time', models.CharField(blank=True, max_length=200)),
                ('highjump_time', models.CharField(blank=True, max_length=200)),
                ('pc1_time', models.CharField(blank=True, max_length=200)),
                ('math_time', models.CharField(blank=True, max_length=200)),
                ('ict_time', models.CharField(blank=True, max_length=200)),
                ('rubiks_time', models.CharField(blank=True, max_length=200)),
                ('table_time', models.CharField(blank=True, max_length=200)),
                ('sprint_time', models.CharField(blank=True, max_length=200)),
                ('badminton_time', models.CharField(blank=True, max_length=200)),
                ('pc3_time', models.CharField(blank=True, max_length=200)),
                ('video_time', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
