# Generated by Django 4.1.7 on 2023-03-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semi_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_desc', models.TextField(blank=True, null=True)),
                ('upteam1', models.CharField(blank=True, max_length=200)),
                ('upteam2', models.CharField(blank=True, max_length=200)),
                ('upteam3', models.CharField(blank=True, max_length=200)),
                ('upteam4', models.CharField(blank=True, max_length=200)),
                ('upteam5', models.CharField(blank=True, max_length=200)),
                ('upteam6', models.CharField(blank=True, max_length=200)),
                ('uptime1', models.CharField(blank=True, max_length=200)),
                ('uptime2', models.CharField(blank=True, max_length=200)),
                ('uptime3', models.CharField(blank=True, max_length=200)),
                ('fteam1', models.CharField(blank=True, max_length=200)),
                ('fteam2', models.CharField(blank=True, max_length=200)),
                ('fteam3', models.CharField(blank=True, max_length=200)),
                ('fteam4', models.CharField(blank=True, max_length=200)),
                ('fteam5', models.CharField(blank=True, max_length=200)),
                ('fteam6', models.CharField(blank=True, max_length=200)),
                ('ftime1', models.CharField(blank=True, max_length=200)),
                ('ftime2', models.CharField(blank=True, max_length=200)),
                ('ftime3', models.CharField(blank=True, max_length=200)),
                ('carsol_pic1', models.ImageField(default='e.png', null=True, upload_to='')),
                ('carsol_pic2', models.ImageField(default='w.png', null=True, upload_to='')),
                ('carsol_pic3', models.ImageField(default='e.png', null=True, upload_to='')),
                ('carsol_pic4', models.ImageField(default='w.png', null=True, upload_to='')),
                ('carsol_pic5', models.ImageField(default='e.png', null=True, upload_to='')),
                ('carsol_pic6', models.ImageField(default='w.png', null=True, upload_to='')),
                ('dsc1', models.TextField(blank=True, null=True)),
                ('dsc2', models.TextField(blank=True, null=True)),
                ('dsc3', models.TextField(blank=True, null=True)),
                ('day1', models.TextField(blank=True, null=True)),
                ('day2', models.TextField(blank=True, null=True)),
                ('day3', models.TextField(blank=True, null=True)),
                ('time1', models.TextField(blank=True, null=True)),
                ('time2', models.TextField(blank=True, null=True)),
                ('time3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
